const express = require("express");
const mongoose = require("mongoose");
const Order = require("../models/Order");
const OrderDispute = require("../models/OrderDispute");
const { requireDatabase, requireAuth, requireRole } = require("../middleware/auth");
const { notifySeller } = require("../services/sellerNotifications");
const { notifyAdmins } = require("../services/adminNotifications");
const { recordAdminAction } = require("../services/adminAudit");
const { saveOrderNotification } = require("../services/orders");
const router = express.Router(); router.use(requireDatabase);
router.post("/", requireAuth, requireRole("customer"), async (req, res, next) => {
  const { orderNumber, fulfillmentId, category, description, evidenceUrls = [] } = req.body || {};
  if (typeof orderNumber !== "string" || !/^SVM-\d{8}-[A-Z0-9]{8}$/.test(orderNumber) || !mongoose.isValidObjectId(fulfillmentId) || !["item_not_received", "item_damaged", "incorrect_item", "refund_issue", "other"].includes(category) || typeof description !== "string" || !description.trim() || description.length > 3000 || !Array.isArray(evidenceUrls) || evidenceUrls.length > 4 || evidenceUrls.some(url => typeof url !== "string" || url.length > 2048 || !url.startsWith("https://"))) return res.status(400).json({ success: false, message: "Dispute details are invalid." });
  try { const order = await Order.findOne({ orderNumber, customerId: req.user._id, paymentStatus: "paid" }); if (!order) return res.status(404).json({ success: false, message: "Paid order not found." }); const fulfillment = order.fulfillments.id(fulfillmentId); if (!fulfillment || fulfillment.status === "cancelled" || fulfillment.status === "refunded") return res.status(409).json({ success: false, message: "This fulfillment is not eligible for a dispute." }); const active = await OrderDispute.exists({ orderId: order._id, fulfillmentId, customerId: req.user._id, status: { $in: ["open", "under_review", "waiting_customer", "waiting_seller"] } }); if (active) return res.status(409).json({ success: false, message: "An active dispute already exists for this fulfillment." }); const dispute = await OrderDispute.create({ orderId: order._id, orderNumber, fulfillmentId, customerId: req.user._id, sellerId: fulfillment.sellerId, category, description: description.trim(), evidenceUrls, history: [{ status: "open", note: "Dispute opened by customer.", actorId: req.user._id }] }); await saveOrderNotification({ recipientId: req.user._id, recipientRole: "customer", type: "order_dispute_opened", title: "Dispute opened", message: `Your dispute for order ${orderNumber} was submitted for review.`, orderId: order._id, fulfillmentId, dedupeKey: `dispute:${dispute._id}:customer-open` }); await notifySeller({ recipientId: fulfillment.sellerId, type: "order_dispute_opened", title: "Order dispute opened", message: `A dispute was opened for order ${orderNumber}.`, targetType: "order_dispute", targetId: dispute._id, dedupeKey: `dispute:${dispute._id}:seller-open` }); await notifyAdmins({ type: "order_dispute_opened", title: "Order dispute needs review", message: `A dispute was opened for order ${orderNumber}.`, targetType: "order_dispute", targetId: dispute._id, dedupeKey: `dispute:${dispute._id}:admin-open` }); res.status(201).json({ success: true, dispute }); }
  catch (error) { next(error); }
});
router.get("/", requireAuth, requireRole("customer"), async (req, res, next) => { try { const rows = await OrderDispute.find({ customerId: req.user._id }).sort({ createdAt: -1 }).limit(100).lean(); res.json({ success: true, disputes: rows.map(({ internalNotes, history, ...row }) => ({ ...row, history: history.map(({ status, at }) => ({ status, at })) })) }); } catch (error) { next(error); } });
router.get("/seller", requireAuth, requireRole("vendor"), async (req, res, next) => { try { const rows = await OrderDispute.find({ sellerId: req.user._id }).select("orderId orderNumber fulfillmentId customerId category description evidenceUrls status resolution history createdAt updatedAt").populate("customerId", "name").sort({ createdAt: -1 }).limit(100).lean(); const disputes = rows.map(({ history, ...row }) => ({ ...row, history: history.map(({ status, at }) => ({ status, at })) })); res.json({ success: true, disputes }); } catch (error) { next(error); } });
router.get("/admin", requireAuth, requireRole("admin"), async (req, res, next) => { try { const filter = ["open", "under_review", "waiting_customer", "waiting_seller", "resolved", "rejected", "closed"].includes(req.query.status) ? { status: req.query.status } : {}; const page = Math.max(1, Number.parseInt(req.query.page, 10) || 1), limit = Math.min(100, Math.max(1, Number.parseInt(req.query.limit, 10) || 25)); const [disputes, total] = await Promise.all([OrderDispute.find(filter).populate("customerId", "name").populate("sellerId", "shopName").sort({ createdAt: -1 }).skip((page - 1) * limit).limit(limit).lean(), OrderDispute.countDocuments(filter)]); res.json({ success: true, disputes, total, page, pages: Math.ceil(total / limit) }); } catch (error) { next(error); } });
router.patch("/admin/:disputeId", requireAuth, requireRole("admin"), async (req, res, next) => { if (!mongoose.isValidObjectId(req.params.disputeId)) return res.status(400).json({ success: false, message: "Invalid dispute ID." }); const { status, note = "", resolution = "" } = req.body || {}; if (!["under_review", "waiting_customer", "waiting_seller", "resolved", "rejected", "closed"].includes(status) || typeof note !== "string" || note.trim().length > 1000 || typeof resolution !== "string" || resolution.length > 2000) return res.status(400).json({ success: false, message: "Dispute update is invalid." }); try { const dispute = await OrderDispute.findById(req.params.disputeId); if (!dispute) return res.status(404).json({ success: false, message: "Dispute not found." }); if (["resolved", "rejected", "closed"].includes(dispute.status)) return res.status(409).json({ success: false, message: "This dispute is finalized." }); const oldStatus = dispute.status; dispute.status = status; dispute.resolution = resolution.trim(); if (note.trim()) dispute.internalNotes = `${dispute.internalNotes}${dispute.internalNotes ? "\n" : ""}${note.trim()}`.slice(-5000); dispute.history.push({ status, note: note.trim(), actorId: req.user._id }); await dispute.save(); await recordAdminAction({ adminId: req.user._id, action: "order_dispute_updated", targetType: "order_dispute", targetId: dispute._id, reason: note.trim(), details: { oldStatus, status } }); await notifySeller({ recipientId: dispute.sellerId, type: `order_dispute_${status}`, title: `Order dispute ${status.replaceAll("_", " ")}`, message: `A dispute for order ${dispute.orderNumber} was updated.`, targetType: "order_dispute", targetId: dispute._id, dedupeKey: `dispute:${dispute._id}:seller:${status}` }); await saveOrderNotification({ recipientId: dispute.customerId, recipientRole: "customer", type: `order_dispute_${status}`, title: `Dispute ${status.replaceAll("_", " ")}`, message: `Your dispute for order ${dispute.orderNumber} was updated.`, orderId: dispute.orderId, fulfillmentId: dispute.fulfillmentId, dedupeKey: `dispute:${dispute._id}:customer:${status}` }); res.json({ success: true, dispute }); } catch (error) { next(error); } });
module.exports = router;
