const express = require("express");
const mongoose = require("mongoose");
const Order = require("../models/Order");
const ReturnRequest = require("../models/ReturnRequest");
const { requireDatabase, requireAuth, requireRole } = require("../middleware/auth");
const { notifySeller } = require("../services/sellerNotifications");
const { notifyAdmins } = require("../services/adminNotifications");
const { recordAdminAction } = require("../services/adminAudit");
const { saveOrderNotification } = require("../services/orders");
const router = express.Router(); router.use(requireDatabase);
const active = ["requested", "under_review", "approved", "return_in_transit", "received"];
router.post("/", requireAuth, requireRole("customer"), async (req, res, next) => {
  const { orderNumber, fulfillmentId, productId, quantity, reason, explanation = "", evidenceUrls = [], resolution = "undecided" } = req.body || {};
  if (typeof orderNumber !== "string" || !/^SVM-\d{8}-[A-Z0-9]{8}$/.test(orderNumber) || !mongoose.isValidObjectId(fulfillmentId) || !mongoose.isValidObjectId(productId) || !Number.isInteger(Number(quantity)) || Number(quantity) < 1 || !["damaged", "not_as_described", "wrong_item", "changed_mind", "other"].includes(reason) || typeof explanation !== "string" || explanation.length > 2000 || !Array.isArray(evidenceUrls) || evidenceUrls.length > 4 || evidenceUrls.some(url => typeof url !== "string" || url.length > 2048 || !url.startsWith("https://")) || !["refund", "replacement", "store_credit", "undecided"].includes(resolution)) return res.status(400).json({ success: false, message: "Return request details are invalid." });
  try {
    const order = await Order.findOne({ orderNumber, customerId: req.user._id, paymentStatus: "paid" });
    if (!order) return res.status(404).json({ success: false, message: "Paid order not found." });
    const fulfillment = order.fulfillments.id(fulfillmentId);
    if (!fulfillment || String(fulfillment.sellerId) === String(req.user._id) || fulfillment.status !== "delivered") return res.status(409).json({ success: false, message: "Only items in a delivered seller fulfillment can be returned." });
    const item = fulfillment.items.find(i => String(i.productId) === String(productId));
    if (!item || Number(quantity) > item.quantity) return res.status(400).json({ success: false, message: "Return quantity exceeds the purchased quantity." });
    if (await ReturnRequest.exists({ orderId: order._id, fulfillmentId, productId, customerId: req.user._id, status: { $in: active } })) return res.status(409).json({ success: false, message: "An active return request already exists for this item." });
    const record = await ReturnRequest.create({ orderId: order._id, orderNumber, fulfillmentId, productId, customerId: req.user._id, sellerId: fulfillment.sellerId, quantity: Number(quantity), reason, explanation: explanation.trim(), evidenceUrls, resolution, history: [{ status: "requested", note: "Return request submitted by customer.", actorId: req.user._id }] });
    await saveOrderNotification({ recipientId: req.user._id, recipientRole: "customer", type: "return_requested", title: "Return request submitted", message: `Your return request for order ${orderNumber} is under review.`, orderId: order._id, fulfillmentId: fulfillment._id, dedupeKey: `return:${record._id}:customer:requested` });
    await notifySeller({ recipientId: fulfillment.sellerId, type: "return_requested", title: "Customer return requested", message: `A return was requested for order ${orderNumber}.`, targetType: "return_request", targetId: record._id, dedupeKey: `return:${record._id}:requested` });
    await notifyAdmins({ type: "return_requested", title: "Return request needs review", message: `A return was requested for order ${orderNumber}.`, targetType: "return_request", targetId: record._id, dedupeKey: `return:${record._id}:admin-requested` });
    res.status(201).json({ success: true, request: record });
  } catch (error) { next(error); }
});
router.get("/", requireAuth, requireRole("customer"), async (req, res, next) => { try { const rows = await ReturnRequest.find({ customerId: req.user._id }).sort({ createdAt: -1 }).limit(100).lean(); const requests = rows.map(({ adminNotes, history, ...row }) => ({ ...row, history: history.map(({ status, at }) => ({ status, at })) })); res.json({ success: true, requests }); } catch (error) { next(error); } });
router.patch("/:requestId/cancel", requireAuth, requireRole("customer"), async (req, res, next) => { if (!mongoose.isValidObjectId(req.params.requestId)) return res.status(400).json({ success: false, message: "Invalid return ID." }); try { const record = await ReturnRequest.findOne({ _id: req.params.requestId, customerId: req.user._id, status: "requested" }); if (!record) return res.status(409).json({ success: false, message: "Only a newly requested return can be cancelled." }); record.status = "cancelled"; record.history.push({ status: "cancelled", note: "Cancelled by customer.", actorId: req.user._id }); await record.save(); res.json({ success: true, request: record }); } catch (error) { next(error); } });
router.get("/seller", requireAuth, requireRole("vendor"), async (req, res, next) => { try { const rows = await ReturnRequest.find({ sellerId: req.user._id }).populate("productId", "title images").populate("customerId", "name").sort({ createdAt: -1 }).limit(100).lean(); const requests = rows.map(({ adminNotes, history, ...row }) => ({ ...row, history: history.map(({ status, at }) => ({ status, at })) })); res.json({ success: true, requests }); } catch (error) { next(error); } });
router.get("/admin", requireAuth, requireRole("admin"), async (req, res, next) => { try { const filter = ["requested", "under_review", "approved", "rejected", "return_in_transit", "received", "resolved", "cancelled"].includes(req.query.status) ? { status: req.query.status } : {}; const page = Math.max(1, Number.parseInt(req.query.page, 10) || 1), limit = Math.min(100, Math.max(1, Number.parseInt(req.query.limit, 10) || 25)); const [requests, total] = await Promise.all([ReturnRequest.find(filter).populate("customerId", "name").populate("sellerId", "shopName").populate("productId", "title").sort({ createdAt: -1 }).skip((page - 1) * limit).limit(limit).lean(), ReturnRequest.countDocuments(filter)]); res.json({ success: true, requests, total, page, pages: Math.ceil(total / limit) }); } catch (error) { next(error); } });
router.patch("/admin/:requestId", requireAuth, requireRole("admin"), async (req, res, next) => {
  if (!mongoose.isValidObjectId(req.params.requestId)) return res.status(400).json({ success: false, message: "Invalid return ID." });
  const { status, note = "" } = req.body || {}; const allowed = ["under_review", "approved", "rejected", "return_in_transit", "received", "resolved"];
  if (!allowed.includes(status) || typeof note !== "string" || note.trim().length > 1000 || (["rejected", "resolved"].includes(status) && !note.trim())) return res.status(400).json({ success: false, message: "Return status and required review note are invalid." });
  try { const record = await ReturnRequest.findById(req.params.requestId); if (!record) return res.status(404).json({ success: false, message: "Return request not found." }); if (["resolved", "rejected", "cancelled"].includes(record.status)) return res.status(409).json({ success: false, message: "This return request is finalized." }); const oldStatus = record.status; record.status = status; record.history.push({ status, note: note.trim(), actorId: req.user._id }); if (note.trim()) record.adminNotes = `${record.adminNotes}${record.adminNotes ? "\n" : ""}${note.trim()}`.slice(-3000); await record.save(); await recordAdminAction({ adminId: req.user._id, action: "return_request_updated", targetType: "return_request", targetId: record._id, reason: note.trim(), details: { oldStatus, status } }); await notifySeller({ recipientId: record.sellerId, type: `return_${status}`, title: `Return request ${status.replaceAll("_", " ")}`, message: `A return request for order ${record.orderNumber} was updated.`, targetType: "return_request", targetId: record._id, dedupeKey: `return:${record._id}:${status}` }); await saveOrderNotification({ recipientId: record.customerId, recipientRole: "customer", type: `return_${status}`, title: `Return ${status.replaceAll("_", " ")}`, message: `Your return request for order ${record.orderNumber} was updated.`, orderId: record.orderId, fulfillmentId: record.fulfillmentId, dedupeKey: `return:${record._id}:customer:${status}` }); res.json({ success: true, request: record }); } catch (error) { next(error); }
});
module.exports = router;
